// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	google "github.com/Alibay/go-kit/google"
	mock "github.com/stretchr/testify/mock"
)

// Captcha is an autogenerated mock type for the Captcha type
type Captcha struct {
	mock.Mock
}

// Verify provides a mock function with given fields: ctx, rq
func (_m *Captcha) Verify(ctx context.Context, rq *google.CaptchaRequest) (bool, error) {
	ret := _m.Called(ctx, rq)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *google.CaptchaRequest) (bool, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *google.CaptchaRequest) bool); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *google.CaptchaRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCaptcha creates a new instance of Captcha. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaptcha(t interface {
	mock.TestingT
	Cleanup(func())
}) *Captcha {
	mock := &Captcha{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
