// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	logger "github.com/Alibay/go-kit/logger"
	mock "github.com/stretchr/testify/mock"
)

// CLoggerFunc is an autogenerated mock type for the CLoggerFunc type
type CLoggerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CLoggerFunc) Execute() logger.CLogger {
	ret := _m.Called()

	var r0 logger.CLogger
	if rf, ok := ret.Get(0).(func() logger.CLogger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.CLogger)
		}
	}

	return r0
}

// NewCLoggerFunc creates a new instance of CLoggerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCLoggerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CLoggerFunc {
	mock := &CLoggerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
