// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorHook is an autogenerated mock type for the ErrorHook type
type ErrorHook struct {
	mock.Mock
}

// Error provides a mock function with given fields: err
func (_m *ErrorHook) Error(err error) {
	_m.Called(err)
}

// NewErrorHook creates a new instance of ErrorHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHook {
	mock := &ErrorHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
