// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	elasticsearch "github.com/Alibay/go-kit/elasticsearch"
	mock "github.com/stretchr/testify/mock"
)

// IndexBuilder is an autogenerated mock type for the IndexBuilder type
type IndexBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx
func (_m *IndexBuilder) Build(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithAlias provides a mock function with given fields: name
func (_m *IndexBuilder) WithAlias(name string) elasticsearch.IndexBuilder {
	ret := _m.Called(name)

	var r0 elasticsearch.IndexBuilder
	if rf, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}

	return r0
}

// WithExplicitMapping provides a mock function with given fields: mapping
func (_m *IndexBuilder) WithExplicitMapping(mapping string) elasticsearch.IndexBuilder {
	ret := _m.Called(mapping)

	var r0 elasticsearch.IndexBuilder
	if rf, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = rf(mapping)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}

	return r0
}

// WithIndex provides a mock function with given fields: name
func (_m *IndexBuilder) WithIndex(name string) elasticsearch.IndexBuilder {
	ret := _m.Called(name)

	var r0 elasticsearch.IndexBuilder
	if rf, ok := ret.Get(0).(func(string) elasticsearch.IndexBuilder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}

	return r0
}

// WithMappingModel provides a mock function with given fields: model
func (_m *IndexBuilder) WithMappingModel(model interface{}) elasticsearch.IndexBuilder {
	ret := _m.Called(model)

	var r0 elasticsearch.IndexBuilder
	if rf, ok := ret.Get(0).(func(interface{}) elasticsearch.IndexBuilder); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elasticsearch.IndexBuilder)
		}
	}

	return r0
}

// NewIndexBuilder creates a new instance of IndexBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndexBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndexBuilder {
	mock := &IndexBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
