// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	monitoring "github.com/Alibay/go-kit/monitoring"
	mock "github.com/stretchr/testify/mock"
)

// MetricsCollector is an autogenerated mock type for the MetricsCollector type
type MetricsCollector struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *MetricsCollector) Execute() monitoring.MetricsCollection {
	ret := _m.Called()

	var r0 monitoring.MetricsCollection
	if rf, ok := ret.Get(0).(func() monitoring.MetricsCollection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(monitoring.MetricsCollection)
		}
	}

	return r0
}

// NewMetricsCollector creates a new instance of MetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsCollector {
	mock := &MetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
