// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	oauth2 "google.golang.org/api/oauth2/v2"
)

// OAuth2 is an autogenerated mock type for the OAuth2 type
type OAuth2 struct {
	mock.Mock
}

// GetGoogleUser provides a mock function with given fields: ctx, token
func (_m *OAuth2) GetGoogleUser(ctx context.Context, token string) (*oauth2.Userinfo, error) {
	ret := _m.Called(ctx, token)

	var r0 *oauth2.Userinfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth2.Userinfo, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth2.Userinfo); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Userinfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOAuth2 creates a new instance of OAuth2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuth2(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuth2 {
	mock := &OAuth2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
