// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	go_kithttp "github.com/Alibay/go-kit/http"

	mock "github.com/stretchr/testify/mock"
)

// ResourcePolicy is an autogenerated mock type for the ResourcePolicy type
type ResourcePolicy struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: ctx, r
func (_m *ResourcePolicy) Resolve(ctx context.Context, r *http.Request) (*go_kithttp.AuthorizationResource, error) {
	ret := _m.Called(ctx, r)

	var r0 *go_kithttp.AuthorizationResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) (*go_kithttp.AuthorizationResource, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) *go_kithttp.AuthorizationResource); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_kithttp.AuthorizationResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourcePolicy creates a new instance of ResourcePolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourcePolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourcePolicy {
	mock := &ResourcePolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
