// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTestServiceServer is an autogenerated mock type for the UnsafeTestServiceServer type
type UnsafeTestServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTestServiceServer provides a mock function with given fields:
func (_m *UnsafeTestServiceServer) mustEmbedUnimplementedTestServiceServer() {
	_m.Called()
}

// NewUnsafeTestServiceServer creates a new instance of UnsafeTestServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTestServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTestServiceServer {
	mock := &UnsafeTestServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
