// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCentrifugoApiServer is an autogenerated mock type for the UnsafeCentrifugoApiServer type
type UnsafeCentrifugoApiServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCentrifugoApiServer provides a mock function with given fields:
func (_m *UnsafeCentrifugoApiServer) mustEmbedUnimplementedCentrifugoApiServer() {
	_m.Called()
}

// NewUnsafeCentrifugoApiServer creates a new instance of UnsafeCentrifugoApiServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCentrifugoApiServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCentrifugoApiServer {
	mock := &UnsafeCentrifugoApiServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
